### ISSUE TITLE
I know this isn't the best best place to contact you

### ISSUE THREAD

**Issue by theblazehen** [dsmiller95/FreqAnalysis#1]
theblaze from fallingsandgame.com here. Trying to get a bunch of us together, to just chat etc. Want to see if any of us still have any old mods etc :)

Got an IRC channel set up: https://kiwiirc.com/client/irc.freenode.net/fallingsand

**Comment by dsmiller95** [comment]
Oh hey! I just saw this now, it must have gone into my spam folder when you first created the issue. What's up? man it was so long ago that I was messing with that game, I don't know if I still have all the stuff I messed around with on my computer still

**Comment by theblazehen** [comment]
Eh, not much. Life :) I must say, mods for those games actually got me into learning ore about computers and stuff. Now got a job as Linux admin. How about you?

Unfortunately I missed you on irc the other day :( GMT+2 here

**Comment by dsmiller95** [comment]
Nice! I definitely had the same interest in computers, and those mods sure helped bolster that. Right now I'm finishing up my 3rd year for a degree in software engineering, looking forward to some cool hobs later on. Maybe we should move this to email, you can reach me at dsmiller95@gmail.com
